
services:
  timory-next:
    container_name: timory-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/timory-next
    working_dir: /usr/src/timory-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# timory-next: localhost: 4000 <=> container:3000
# timory-api: localhost: 4001 <=> container:3003
# timory-batch: localhost: 4002 <=> container:3004
